# 01. Importing Libraries

In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd

# 02. Importing Data

In [3]:
demo = pd.read_csv('../../IronHack/Unit 5 - EDA and Inferential Stats/Group Project/Data/df_final_demo.txt')

In [4]:
clients = pd.read_csv('../../IronHack/Unit 5 - EDA and Inferential Stats/Group Project/Data/df_final_experiment_clients.txt')

In [23]:
demo.shape

(70609, 9)

In [24]:
clients.shape

(70609, 2)

# 03. Analysis and Cleaning

In [7]:
clients.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

#### Cleaning clients

In [9]:
clients.dtypes

client_id    int64
Variation      str
dtype: object

In [10]:
# renaming columns for better understanding and best practices
clients.rename(columns={'Variation': 'group_test'}, inplace=True)

In [11]:
clients.head()

   client_id group_test
0    9988021       Test
1    8320017       Test
2    4033851    Control
3    1982004       Test
4    9294070    Control

In [ ]:
# checking for nulls
clients.isnull().sum()

client_id         0
group_test    20109
dtype: int64

In [15]:
clients['group_test'].value_counts()

group_test
Test       26968
Control    23532
Name: count, dtype: int64

For now, the nulls on the column 'group_test' will be kept and no imputation/drop will be done. Most likely we will drop the rows in the future, once possible dfs are merged or just ignored on possible groupby in python or SQL

In [16]:
# trimming whitespaces and converting to lowercase for consistency
clients['group_test'] = clients['group_test'].str.strip().str.lower()

In [17]:
clients['group_test'].value_counts()

group_test
test       26968
control    23532
Name: count, dtype: int64

In [ ]:
# checking for duplicates
clients.duplicated().sum()

np.int64(0)

In [ ]:
# exporting clients cleaned data
clients.to_csv('../../IronHack/Unit 5 - EDA and Inferential Stats/Group Project/Data/df_final_experiment_clients_cleaned.csv', index=False)

#### Cleaning demo

In [26]:
demo.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [27]:
demo.dtypes

client_id             int64
clnt_tenure_yr      float64
clnt_tenure_mnth    float64
clnt_age            float64
gendr                   str
num_accts           float64
bal                 float64
calls_6_mnth        float64
logons_6_mnth       float64
dtype: object

In [28]:
# renaming columns for better understanding and best practices
demo.rename(columns={'clnt_tenure_yr': 'tenure_years', 'clnt_tenure_mnth': 'tenure_months', 'clnt_age': 'age', 'gendr': 'gender', 'bal': 'balance', 'calls_6_mnth': 'calls_last_6_months', 'logons_6_mnth': 'logons_last_6_months'}, inplace=True)

In [30]:
# checking if the renaming was successful
demo.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [31]:
demo.isnull().sum()

client_id                0
tenure_years            14
tenure_months           14
age                     15
gender                  14
num_accts               14
balance                 14
calls_last_6_months     14
logons_last_6_months    14
dtype: int64

In [33]:
# checking the rows that have null values (if the same rows or spread around the dataset)
demo[demo.isnull().any(axis=1)]

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months
4164,7402828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8316,355337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8677,8412164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9583,4666211,8.0,106.0,NaN,F,2.0,42550.55,4.0,7.0
13444,2222915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18066,4876926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,5277910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28432,7616759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35323,8191345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43518,1227228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46076,8611797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47189,5144725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49846,1037867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63701,1618749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66219,6021001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Most rows are the same. For now, the nulls will be kept and no imputation/drop will be done. Most likely we will drop the rows in the future, once possible dfs are merged or just ignored on possible groupby in python or SQL

In [34]:
# stripping whitespaces for the column gender
demo['gender'] = demo['gender'].str.strip()

In [37]:
demo['gender'].value_counts()

gender
U    24122
M    23724
F    22746
X        3
Name: count, dtype: int64

In [38]:
# replacing X for U in the gender column
demo['gender'] = demo['gender'].replace('X', 'U')

In [39]:
# checking if replacing was successful
demo['gender'].value_counts()

gender
U    24125
M    23724
F    22746
Name: count, dtype: int64

In [40]:
# checking for duplicates
demo.duplicated().sum()

np.int64(0)

In [41]:
# exporting cleaned demo dataset
demo.to_csv('../../IronHack/Unit 5 - EDA and Inferential Stats/Group Project/Data/df_final_demo_cleaned.csv', index=False)