## Import libraries

In [2]:
import pandas as pd

## Loading the Datasets

In [3]:
info = pd.read_csv("../Data/Clean_data/df_final_demo_cleaned.csv")
version = pd.read_csv("../Data/Clean_data/df_final_experiment_clients_cleaned.csv")

In [4]:
info.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [5]:
info.shape

(70609, 9)

In [6]:
version.head()

   client_id group_test
0    9988021       test
1    8320017       test
2    4033851    control
3    1982004       test
4    9294070    control

In [7]:
version.shape

(70609, 2)

## Merging the Datasets

In [8]:
info_com = pd.merge(info, version, on = "client_id")

In [9]:
info_com.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months,group_test
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,control

## Cleaning the Dataset

In [10]:
info_com["group_test"].isna().sum()

np.int64(20109)

In [11]:
info_com.dropna(subset=["group_test"], inplace = True)

In [12]:
info_com.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months,group_test
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,control

In [13]:
info_com.isna().sum()

client_id                0
tenure_years            12
tenure_months           12
age                     13
gender                  12
num_accts               12
balance                 12
calls_last_6_months     12
logons_last_6_months    12
group_test               0
dtype: int64

In [14]:
info_com.dropna(thresh = 9).shape

# for the demographics, we'll need the most accurate data possible so we are dropping all the rows that aren't complete.
# which, by the way, are the same. all the null values are concentrated in 12 rows as you can see
# then there is a row with a null value in age. In that row we'll introduce the average.

(50488, 10)

In [15]:
info_com.dropna(thresh = 9, inplace = True)

In [16]:
# we fill the null value for age

info_com["age"] = info_com["age"].fillna(info_com["age"].mean())

## Columns

We'll create categories for age and we'll remove columns which aren't relevant for our visualizations.

In [17]:
info_com.columns

Index(['client_id', 'tenure_years', 'tenure_months', 'age', 'gender',
       'num_accts', 'balance', 'calls_last_6_months', 'logons_last_6_months',
       'group_test'],
      dtype='str')

In [18]:
info_com.drop(columns = ['calls_last_6_months', 'logons_last_6_months'], inplace = True)

In [19]:
def age_label(age):
    if age <18:
        return "Adolescent"
    elif age >= 18 and age <= 30:
        return "Young dults"
    elif age >= 31 and age < 60:
        return "Middle-aged"
    elif age >= 60 and age <= 90:
        return "Senior"
    else:
        return "Time to die"

info_com["age_label"] = info_com["age"].apply(age_label)
info_com.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,group_test,age_label
0,836976,6.0,73.0,60.5,U,2.0,45105.30,test,Senior
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,control,Middle-aged
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,test,Middle-aged
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,test,Middle-aged
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,control,Middle-aged

In [20]:
info_com.columns

Index(['client_id', 'tenure_years', 'tenure_months', 'age', 'gender',
       'num_accts', 'balance', 'group_test', 'age_label'],
      dtype='str')

In [21]:
info_com = info_com[['client_id', 'group_test', 'age', 'age_label', 'gender',
                    'num_accts', 'balance', 'tenure_years', 'tenure_months']]

# reordering columns to keep it super clean

In [22]:
info_com.head()

,client_id,group_test,age,age_label,gender,num_accts,balance,tenure_years,tenure_months
0,836976,test,60.5,Senior,U,2.0,45105.30,6.0,73.0
1,2304905,control,58.0,Middle-aged,U,2.0,110860.30,7.0,94.0
2,1439522,test,32.0,Middle-aged,U,2.0,52467.79,5.0,64.0
3,1562045,test,49.0,Middle-aged,M,2.0,67454.65,16.0,198.0
4,5126305,control,33.0,Middle-aged,F,2.0,103671.75,12.0,145.0

In [23]:
info_com.to_csv("../Data/Clean_data/info_com.csv", index = False)